# Generated by Django 5.2.3 on 2025-06-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'bus', 'favorite_time'), name='unique_user_bus_time'),
        ),
    ]
